### ISSUE TITLE
最高版本不是4.8吗为什么会提示让更新到4.9

### ISSUE THREAD

**Issue by yiluoiro** [ZIDC/com.cjzwjdm#2]
![Screenshot_2022-08-17-16-46-18-813_com.cjzwjdm.jpg](https://user-images.githubusercontent.com/38562351/185075951-63421520-f54f-4ac5-92e3-03b3782f69da.jpg)

**Comment by yiluoiro** [comment]
原来是你没更新库文件啊![1a2708fe7b8ef0b2.jpg](https://user-images.githubusercontent.com/38562351/185078373-82e53105-5212-4a70-830c-b64e7c04ce0a.jpg)

**Comment by ZIDC** [comment]
> 原来是你没更新库文件啊![1a2708fe7b8ef0b2.jpg](https://user-images.githubusercontent.com/38562351/185078373-82e53105-5212-4a70-830c-b64e7c04ce0a.jpg)

已经关闭更新提示了

**Comment by yiluoiro** [comment]
有兴趣一起来用裕语言开发QQ机器人项目嘛

**Comment by yiluoiro** [comment]
> 有兴趣一起来用裕语言开发QQ机器人项目嘛

![Screenshot_2022-08-17-15-05-23-790_com.iapp.app.jpg](https://user-images.githubusercontent.com/38562351/185083761-46d7dd73-86db-433a-9772-097c8ac0b9e8.jpg)![正在上传 a3{faba361} (354ef5dc-1ff2-487d-8329-52c2e20aa333 id=0x7f0a03c6)…]()
项目目前进度

**Comment by ZIDC** [comment]
> 有兴趣一起来用裕语言开发QQ机器人项目嘛

不了不了，上班没啥时间

**Comment by yiluoiro** [comment]
> > 有兴趣一起来用裕语言开发QQ机器人项目嘛
> 
> 不了不了，上班没啥时间

哦哦
